name: Weekly Data Preparation and Deployment

on:
  push:
    branches:
      - main
  schedule:
    # Runs at 16:00 on Monday (UTC) or 9 pacific
    - cron: '0 16 * * 1'
  # Allows manual triggering of the workflow
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  prepare-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Run data preparation script
        run: ./bin/pull_data.sh && python bin/prepare_data.py

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: prepare-data
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4